# Generated by Django 2.1.5 on 2019-08-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
